"""Tests for the final technical-feature selection."""

from quant_equity.features import (
    SELECTED_TECHNICAL_FEATURE_COLUMNS,
    TECHNICAL_MODEL_FEATURE_COLUMNS,
)

EXPECTED_SELECTED_TECHNICAL_FEATURE_COLUMNS = (
    "amihud_illiquidity_20d_sector_neutral",
    "reversal_1m_sector_neutral",
    "volatility_60d_sector_neutral",
    "distance_sma_50d_sector_neutral",
    "beta_60d_market_sector_neutral",
    "return_3m_sector_neutral",
    "max_drawdown_126d_sector_neutral",
    "average_dollar_volume_20d_sector_neutral",
)


def test_selected_feature_count_is_valid() -> None:
    """The selected set must satisfy the Step 6 requirement."""
    assert 8 <= len(SELECTED_TECHNICAL_FEATURE_COLUMNS) <= 15


def test_selected_features_match_frozen_decision() -> None:
    """The code must contain the approved frozen selection."""
    assert SELECTED_TECHNICAL_FEATURE_COLUMNS == EXPECTED_SELECTED_TECHNICAL_FEATURE_COLUMNS


def test_selected_features_are_unique() -> None:
    """A feature must not appear more than once."""
    assert len(SELECTED_TECHNICAL_FEATURE_COLUMNS) == len(set(SELECTED_TECHNICAL_FEATURE_COLUMNS))


def test_selected_features_exist_in_full_feature_set() -> None:
    """Every selected feature must be generated by the feature pipeline."""
    assert set(SELECTED_TECHNICAL_FEATURE_COLUMNS).issubset(set(TECHNICAL_MODEL_FEATURE_COLUMNS))


def test_full_feature_set_remains_available() -> None:
    """Research and audit outputs must retain the original 19 signals."""
    assert len(TECHNICAL_MODEL_FEATURE_COLUMNS) == 19


def test_reversal_is_kept_instead_of_duplicate_return() -> None:
    """Keep reversal and exclude its exact inverse duplicate."""
    assert "reversal_1m_sector_neutral" in SELECTED_TECHNICAL_FEATURE_COLUMNS
    assert "return_1m_sector_neutral" not in SELECTED_TECHNICAL_FEATURE_COLUMNS


def test_non_varying_feature_is_excluded() -> None:
    """The zero-volume feature cannot provide a ranking."""
    assert "zero_volume_ratio_60d_sector_neutral" not in SELECTED_TECHNICAL_FEATURE_COLUMNS
