from __future__ import annotations

import pandas as pd
import streamlit as st
from components.data_quality_charts import (
    validation_suite_figure,
    violation_figure,
)
from components.shell import render_page_header
from data_access import load_dashboard_source

from quant_equity.reporting.dashboard_data_quality import (
    failed_controls,
    quality_headline,
    standardize_check_table,
    suite_summary,
)

SOURCE_IDS = (
    "leakage_checks",
    "panel_readiness",
    "walk_forward_readiness",
    "risk_checks",
    "covariance_checks",
    "portfolio_checks",
    "execution_checks",
    "robustness_inventory",
)


render_page_header(
    "Data Quality",
    (
        "Operational controls for point-in-time integrity, walk-forward readiness, "
        "risk estimation, portfolio construction, execution, and robustness."
    ),
)

st.caption(
    
        "This page surfaces persisted validation artifacts generated by the research "
        "pipeline. It does not recompute, suppress, or override failed controls."
    
)

sources = {
    source_id: load_dashboard_source(source_id)
    for source_id in SOURCE_IDS
}
summary = suite_summary(sources)
headline = quality_headline(summary)
failures = failed_controls(sources)

metric_row_one = st.columns(3)
metric_row_one[0].metric(
    "Validation suites",
    f"{headline['passing_suites']}/{headline['suites']} PASS",
)
metric_row_one[1].metric(
    "Controls passed",
    f"{headline['passed_checks']}/{headline['checks']}",
)
metric_row_one[2].metric(
    "Recorded violations",
    str(headline["violations"]),
)

metric_row_two = st.columns(2)
metric_row_two[0].metric(
    "Failed controls",
    str(headline["failed_checks"]),
)
metric_row_two[1].metric(
    "Escalations",
    str(len(failures)),
)

if failures.empty:
    st.success(
        
            "No non-passing controls are present in the canonical validation "
            "artifacts loaded by the dashboard."
        
    )
else:
    st.error(
        
            f"{len(failures)} control(s) require attention. Review the escalation "
            "table before treating the pipeline as production-ready."
        
    )

st.subheader("Control-suite status")
st.caption(
    
        "Each bar represents persisted checks from one stage of the research and "
        "portfolio pipeline."
    
)

left, right = st.columns(2)
with left:
    st.markdown("**Passed controls by suite**")
    st.plotly_chart(validation_suite_figure(summary), width="stretch")

with right:
    st.markdown("**Recorded violations by suite**")
    st.plotly_chart(violation_figure(summary), width="stretch")

summary_display = summary.loc[
    :,
    [
        "suite",
        "checks",
        "passed",
        "failed",
        "violations",
        "status",
    ],
].copy()
summary_display = summary_display.rename(
    columns={
        "suite": "Suite",
        "checks": "Controls",
        "passed": "Passed",
        "failed": "Failed",
        "violations": "Violations",
        "status": "Status",
    }
)
st.dataframe(summary_display, width="stretch", hide_index=True)

st.subheader("Escalations")
st.caption(
    
        "Any control whose persisted status is not PASS is surfaced here without "
        "reinterpretation."
    
)

if failures.empty:
    st.info("No escalations. All loaded validation controls are PASS.")
else:
    st.dataframe(
        failures,
        width="stretch",
        hide_index=True,
        height=320,
    )

st.subheader("Detailed validation evidence")
st.caption(
    
        "Expand a validation family to inspect its underlying checks, violation "
        "counts, and stored descriptions."
    
)

for source_id in SOURCE_IDS:
    display = standardize_check_table(source_id, sources[source_id])
    label = summary.loc[summary["source_id"].eq(source_id), "suite"].iloc[0]
    suite_row = summary.loc[summary["source_id"].eq(source_id)].iloc[0]

    expander_label = (
        f"{label} · {int(suite_row['passed'])}/{int(suite_row['checks'])} PASS"
    )
    with st.expander(expander_label, expanded=False):
        columns = [
            "Check",
            "Status",
            "Violations",
            "Description",
        ]
        if source_id == "robustness_inventory":
            columns = [
                "Check",
                "Category",
                "Status",
                "Violations",
                "Subchecks",
                "Passed",
                "Description",
            ]

        st.dataframe(
            display.loc[:, columns],
            width="stretch",
            hide_index=True,
            height=min(520, 90 + 34 * len(display)),
        )

st.subheader("Pipeline date boundaries")
st.caption(
    
        "The dashboard distinguishes model signal dates, evaluated portfolio dates, "
        "and raw benchmark availability to avoid conflating research freshness."
    
)

alpha = load_dashboard_source("alpha_signal")
performance = load_dashboard_source("performance_net_daily")
benchmark = load_dashboard_source("benchmark_spy")

alpha_dates = pd.to_datetime(alpha["as_of_date"], errors="coerce").dropna()
performance_dates = pd.to_datetime(performance["date"], errors="coerce").dropna()
benchmark_dates = pd.to_datetime(benchmark["date"], errors="coerce").dropna()

date_columns = st.columns(3)
date_columns[0].metric(
    "Latest signal date",
    alpha_dates.max().strftime("%Y-%m-%d") if not alpha_dates.empty else "N/A",
)
date_columns[1].metric(
    "Latest evaluated day",
    (
        performance_dates.max().strftime("%Y-%m-%d")
        if not performance_dates.empty
        else "N/A"
    ),
)
date_columns[2].metric(
    "Benchmark raw latest",
    (
        benchmark_dates.max().strftime("%Y-%m-%d")
        if not benchmark_dates.empty
        else "N/A"
    ),
)

st.caption(
    
        "A later raw benchmark date does not imply a later evaluated OOS signal. "
        "These boundaries belong to different stages of the pipeline."
    
)
